import type { DataJson, MappingOut } from "../../utils/types";
import { BaseScannerParser, type ParserInput, type ParseContext } from "./parser";
import { ScannerParsingError } from "../errors/ScannerParsingError";

function extractBurpMeta(html: string): { burpVersion?: string; exportTime?: string } {
  // Example line near end of report:
  // "Report generated by Burp Suite ... v2025.12.5, at Tue Feb 03 16:34:58 GMT 2026."
  const re = /Report generated by Burp Suite[\s\S]*?\bv([0-9]+\.[0-9]+\.[0-9]+)\b,\s*at\s*([^.<]+)\./i;
  const m = re.exec(html);
  return { burpVersion: m?.[1], exportTime: m?.[2]?.trim() };
}

export class BurpHtmlParser extends BaseScannerParser {
  constructor(scannerKey: string) {
    super(scannerKey);
  }

  public async parse(
    input: ParserInput,
    data: DataJson,
    ctx?: ParseContext
  ): Promise<MappingOut> {
    const html = await this.loadText(input);

    const expectedByTest = this.buildExpectedCWEsByTest(data);

    // --- infer scanProfile + updatedAt from HTML footer, unless ctx overrides ---
    const { burpVersion, exportTime } = extractBurpMeta(html);
    const inferredScanProfile = burpVersion ? `v${burpVersion}` : this.scannerKey;
    const inferredUpdatedAt = this.parseEpochFromIsoOrFallback(exportTime) ?? this.nowEpoch();
    const scanProfile = ctx?.scanProfile ?? inferredScanProfile;
    const updatedAt = ctx?.updatedAt ?? inferredUpdatedAt;

    // testName -> set(cweId)
    const detectedByTest = new Map<string, Set<number>>();

    // In Burp HTML:
    // - Vulnerability types are rendered as <span class="BODH0" id="...">...</span>
    // - Instances under each vuln type appear as <span class="BODH1" id="...">...http://host:port/...</span>
    //
    // CWEs for the vuln type appear within the same block (typically under "Vulnerability classifications"),
    // and should be applied to all instances (BODH1) within that block.

    //Loop through BODH0 blocks (each representing a vulnerability type), extract CWEs and map to any BODH1 instance URLs within the same block
    const bodh0Re = /<span\s+class="BODH0"[^>]*>[\s\S]*?<\/span>/gi;
    const bodh0Matches: Array<{ start: number }> = [];
    let h0: RegExpExecArray | null;
    while ((h0 = bodh0Re.exec(html)) !== null) {
      bodh0Matches.push({ start: h0.index });
    }

    for (let i = 0; i < bodh0Matches.length; i++) {
      const start = bodh0Matches[i].start;
      const end = i + 1 < bodh0Matches.length ? bodh0Matches[i + 1].start : html.length;
      const blockHtml = html.slice(start, end);

      // 1) Extract CWE IDs from this vulnerability-type block
      const cwes = new Set<number>();
      const cweRe = /\bCWE-(\d+)\b/gi;
      let cm: RegExpExecArray | null;
      while ((cm = cweRe.exec(blockHtml)) !== null) {
        const cweId = Number(cm[1]);
        if (!Number.isFinite(cweId) || cweId <= 0) continue;
        cwes.add(cweId);
      }
      if (cwes.size === 0) continue;

      // 2) Map this vuln-type block to tests.
      // If a summary table is present, Burp has detected the vulnerability in a single test case so is all in BODH0 block.
      // Otherwise, use BODH1 entries (multi-instance format).
      const hasSummaryTable = /<table\b[^>]*class="summary_table"[^>]*>/i.test(blockHtml);

      if (hasSummaryTable) {
      // Single-instance style: host/port in Summary table
      // Matches: <td><b>http://localhost:10011</b></td>
      const hostRe = /<td>\s*<b>\s*(https?:\/\/[^<\s"]+)\s*<\/b>\s*<\/td>/i;
      const hm = hostRe.exec(blockHtml);
      const hostUrl = hm?.[1]?.trim();

      if (hostUrl) {
          const portMatch = /:(\d+)\b/.exec(hostUrl);
          const port = portMatch ? Number(portMatch[1]) : NaN;

          const testName = this.portToTestName(port);
          if (testName) {
            if (!detectedByTest.has(testName)) detectedByTest.set(testName, new Set<number>());
            const set = detectedByTest.get(testName)!;
            for (const cwe of cwes) set.add(cwe);
          }
      }
      } else {
        // Multi-instance style: URLs appear in BODH1 headings
        const bodh1Re = /<span\s+class="BODH1"[^>]*>[\s\S]*?<\/span>/gi;
        let h1: RegExpExecArray | null;
        while ((h1 = bodh1Re.exec(blockHtml)) !== null) {
          const sub = h1[0];

          const urlMatch = /\bhttps?:\/\/[^\s<"]+/i.exec(sub);
          if (!urlMatch) continue;

          const url = urlMatch[0];
          const portMatch = /:(\d+)\b/.exec(url);
          const port = portMatch ? Number(portMatch[1]) : NaN;

          const testName = this.portToTestName(port);
          if (!testName) continue;

          if (!detectedByTest.has(testName)) detectedByTest.set(testName, new Set<number>());
          const set = detectedByTest.get(testName)!;
          for (const cwe of cwes) set.add(cwe);
        }
      }
    }

    // Error handling
    if (detectedByTest.size === 0) {
      throw new ScannerParsingError(
        "Failed to parse Burp HTML report. Missing key attributes or findings."
      );
    }

    const testUniverse = (ctx?.expectedTests?.length
      ? ctx.expectedTests
      : Array.from(detectedByTest.keys())
    ).filter((t) => expectedByTest.has(t)); // keep it aligned to framework tests

    const testsOut = Array.from(new Set(testUniverse))
      .sort(this.sortTestNames)
      .map((test) => {
        const expected = expectedByTest.get(test) ?? new Set<number>();
        const detectedAll = detectedByTest.get(test) ?? new Set<number>();

        const detectedCWEs = Array.from(detectedAll)
          .filter((c) => expected.has(c))
          .sort((a, b) => a - b);

        const undetectedCWEs = Array.from(expected)
          .filter((c) => !detectedAll.has(c))
          .sort((a, b) => a - b);

        return { test, detectedCWEs, undetectedCWEs, updatedAt };
      });

    const out: MappingOut = {
      [this.scannerKey]: {
        scanProfile,
        tests: testsOut,
      },
    };

    this.lastResult = out;
    return out;
  }
}

// Specific Burp scan variants (same logic apart from names)
export class BurpLightHtmlParser extends BurpHtmlParser {
  constructor() {
    super("Burp Suite - Light Scan");
  }
}

export class BurpDeepHtmlParser extends BurpHtmlParser {
  constructor() {
    super("Burp Suite - Deep Scan");
  }
}